### ISSUE TITLE
SmartInput使用期限已到，无法为您自动切换输入法

### ISSUE THREAD

**Issue by M1sury** [SmartInput/SmartInput#1]
环境：云桌面（深信服的VDI）
IDEA可以下载安装插件，但是没办法使用。
是需要联网下载一些东西吗？

**Comment by M1sury** [comment]
没办法截图，桌面有公司水印

**Comment by NekoFox6** [comment]
我的也是，按照公众号上面的找反馈根本找不到😡

**Comment by xxxtai** [comment]
公众号联系我了吗，联系我我好给你解决方法发自我的手机-------- 原始邮件 --------发件人： GWT ***@***.***>日期： 2023年9月26日周二 下午2:48收件人： SmartInput/SmartInput ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1)
我的也是，按照公众号上面的找反馈根本找不到😡

**Comment by NekoFox6** [comment]
已联系，在【开发效率】微信公众号已发UID，再去看应该很快就能发现我，拜托作者大大了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmartInput/SmartInput"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月26日(星期二) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1)





 公众号联系我了吗，联系我我好给你解决方法发自我的手机-------- 原始邮件 --------发件人： GWT ***@***.***&gt;日期： 2023年9月26日周二 下午2:48收件人： SmartInput/SmartInput ***@***.***&gt;抄送： Subscribed ***@***.***&gt;主    题： Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1) 
 我的也是，按照公众号上面的找反馈根本找不到😡

**Comment by M1sury** [comment]
> 已联系，在【开发效率】微信公众号已发UID，再去看应该很快就能发现我，拜托作者大大了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SmartInput/SmartInput" ***@***.***&gt;; 发送时间:&nbsp;2023年9月26日(星期二) 下午3:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1) 公众号联系我了吗，联系我我好给你解决方法发自我的手机-------- 原始邮件 --------发件人： GWT ***@***.***&gt;日期： 2023年9月26日周二 下午2:48收件人： SmartInput/SmartInput ***@***.***&gt;抄送： Subscribed ***@***.***&gt;主 题： Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1) 我的也是，按照公众号上面的找反馈根本找不到😡 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

问下解决了吗？

**Comment by NekoFox6** [comment]
问题已经解决，需要一个离线激活码，输入后就成功激活了，可以正常使用，好评！
（后期如果出付费版本的话也是希再多加些功能，例如识别更多的开发环境以及支持更多的快捷操作热键等）


General&nbsp;狐弓
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmartInput/SmartInput"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月28日(星期四) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1)





  
已联系，在【开发效率】微信公众号已发UID，再去看应该很快就能发现我，拜托作者大大了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SmartInput/SmartInput" @.&gt;; 发送时间:&nbsp;2023年9月26日(星期二) 下午3:11 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1) 公众号联系我了吗，联系我我好给你解决方法发自我的手机-------- 原始邮件 --------发件人： GWT @.&gt;日期： 2023年9月26日周二 下午2:48收件人： SmartInput/SmartInput @.&gt;抄送： Subscribed @.&gt;主 题： Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1) 我的也是，按照公众号上面的找反馈根本找不到😡 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
问下解决了吗？

**Comment by M1sury** [comment]
> 问题已经解决，需要一个离线激活码，输入后就成功激活了，可以正常使用，好评！ （后期如果出付费版本的话也是希再多加些功能，例如识别更多的开发环境以及支持更多的快捷操作热键等） General&nbsp;狐弓 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SmartInput/SmartInput" ***@***.***&gt;; 发送时间:&nbsp;2023年9月28日(星期四) 下午2:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1) 已联系，在【开发效率】微信公众号已发UID，再去看应该很快就能发现我，拜托作者大大了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SmartInput/SmartInput" @.&gt;; 发送时间:&nbsp;2023年9月26日(星期二) 下午3:11 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1) 公众号联系我了吗，联系我我好给你解决方法发自我的手机-------- 原始邮件 --------发件人： GWT @.&gt;日期： 2023年9月26日周二 下午2:48收件人： SmartInput/SmartInput @.&gt;抄送： Subscribed @.&gt;主 题： Re: [SmartInput/SmartInput] SmartInput使用期限已到，无法为您自动切换输入法 (Issue #1) 我的也是，按照公众号上面的找反馈根本找不到😡 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 问下解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的谢谢,明白了.昨天还在微信公众号上私信了.但是没回复,害
